site_name: Terraform Exporter for SAP BTP
theme:
  name: material
  features:
    - navigation.footer
  logo: img/logo.svg
  palette:
    primary: black
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
repo_url: https://github.com/SAP/terraform-exporter-btp
extra:
    generator: false
copyright: Copyright © 2025 SAP SE or SAP affiliate company. All rights reserved.
nav:
  - Home: index.md
  - Installation: install.md
  - Usage:
    - Prerequisites: prerequisites.md
    - Getting Started: gettingstarted.md
    - Limitations: limitations.md
    - Commands List: btptf.md
  - Concepts: concepts.md
  - Security Considerations: security.md
  - Terraform Configuration Improvements: tfcodeimprovements.md
