site_name: Terraform Exporter for SAP BTP
theme:
  name: material
  features:
    - navigation.footer
  logo: img/logo.svg
  palette:
    primary: black
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
repo_url: https://github.com/SAP/terraform-exporter-btp
extra:
  generator: false
copyright: Copyright © 2025 SAP SE or SAP affiliate company. All rights reserved.
nav:
  - Home: index.md
  - Architecture & Concepts: 
      - How the btptf CLI Works: concepts.md
      - How the btptf CLI Refines the Generated Configurations: tfcodeimprovements.md
  - Installation: install.md
  - Commands Reference: btptf.md
  - Quick Start Guide:
      - Prerequisites: prerequisites.md
      - How to Export Resources: gettingstarted.md
  - Advanced Configuration:
      - How to Add a Remote Backend: remotebackend.md
      - How to Resume Failed Exports: resume.md
  - Limitations: limitations.md
  - Security Considerations: security.md
  - Troubleshooting: troubleshooting.md
