name: 🐞 Bug report
description: File a bug/issue to help us improve
title: "[BUG]"
labels: [bug, needs-triage]
body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
        - label: I have searched the existing issues
          required: true
  - type: input
    attributes:
      label: What version of the Terraform exporter are you using?
      description: What version of the Terraform exporter for SAP BTP are you using?
      placeholder: 0.1.0-beta1
    validations:
      required: true
  - type: input
    attributes:
      label: What version of the Terraform CLI are you using?
      description: What version of the Terraform CLI are you using?
      placeholder: 1.9.0
    validations:
      required: true
  - type: dropdown
    id: area
    attributes:
      label: What type of issue are you facing
      description: What type of issue are you facing?
      options:
        - bug report
        - documentation issue
        - regression (a behavior that used to work and stopped in a new version)
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe the bug
      description: Provide a clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected Behavior
      description: A concise description of what you expected to happen.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: |
        Describe the steps to reproduce the observed behavior.

      placeholder: |
        1. Execute the command `btptfexport --help`
        2. Execute the command ...
    validations:
      required: false
  - type: textarea
    attributes:
      label: User's Role Collections
      description: |
        List the role collections that are assigned to the user executing the CLI.

        This is especially important if you are facing authorization issues like errors with status code 403.
      placeholder: |
        - Global Account Viewer
        - Subaccount Administrator
    validations:
      required: false
  - type: textarea
    attributes:
      label: Add screenshots to help explain your problem
      description: |
        If applicable, add screenshots to help explain your problem.

        Tip: You can attach images or files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional context
      description: |
        Add any other context like links or references about the problem here. Anything that will give us more context about the issue you are encountering!

        Tip: You can attach images or files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
