name: Deploy gh-page
# Pages will be built against a specific tag when releases
# Additionally trigger manually
on:
  workflow_dispatch:
  workflow_call:
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 20241106+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v6
        with:
          python-version: 3.x
      - run: pip install mkdocs-material==9.5.33
      - run: mkdocs gh-deploy --force