name: Integration Test

on:
  workflow_dispatch:
  workflow_call:

permissions:
  contents: read

env:
  TF_VERSION: 1.10.5

jobs:
#  test-json-inventory:
#    name: Integration Test JSON Inventory
#    runs-on: ubuntu-latest
#    timeout-minutes: 5
#    steps:
#      - name: Checkout repository
#        uses: actions/checkout@v4
#
#      - name: Setup Go
#        uses: actions/setup-go@v5
#        with:
#          go-version-file: 'go.mod'
#          cache: true
#
#      - name: Download dependencies
#        run: go mod download
#
#      - name: Install Terraform Exporter CLI
#        run: make install
#
#      - name: Setup Terraform CLI
#        uses: hashicorp/setup-terraform@v3.1.2
#        with:
#          terraform_version: ${{ env.TF_VERSION }}
#          terraform_wrapper: false
#
#      - name: JSON inventory for Directory
#        run: |
#          export BTP_USERNAME=${{ secrets.BTP_USERNAME }}
#          export BTP_PASSWORD=${{ secrets.BTP_PASSWORD }}
#          export BTP_GLOBALACCOUNT=${{ secrets.BTP_GLOBALACCOUNT }}
#          btptf create-json -d ${{ secrets.BTP_DIRECTORY }} -p integrationTestDirectory.json
#          jq '.BtpResources[] |= (.Values |= sort)' integrationTestDirectory.json > temp.json && mv temp.json integrationTestDirectory.json
#          diff <(jq -S . integrationTestDirectory.json) <(jq -S . integration-test/exporter-reference-data/json-inventory/integrationTestDirectoryReference.json) || echo "JSON inventory for directory is not as expected"
#
#      - name: JSON inventory for Subaccount
#        if: ${{ success() }} || ${{ failure() }}
#        run: |
#          export BTP_USERNAME=${{ secrets.BTP_USERNAME }}
#          export BTP_PASSWORD=${{ secrets.BTP_PASSWORD }}
#          export BTP_GLOBALACCOUNT=${{ secrets.BTP_GLOBALACCOUNT }}
#          btptf create-json -s ${{ secrets.BTP_SUBACCOUNT }} -p integrationTestSubaccount.json
#          jq '.BtpResources[] |= (.Values |= sort)' integrationTestSubaccount.json > temp.json && mv temp.json integrationTestSubaccount.json
#          diff <(jq -S . integrationTestSubaccount.json) <(jq -S . integration-test/exporter-reference-data/json-inventory/integrationTestSubaccountReference.json) || echo "JSON inventory for subaccount is not as expected"
#
#      - name: JSON inventory for Cloud Foundry Org
#        if: ${{ success() }} || ${{ failure() }}
#        run: |
#          export CF_USER=${{ secrets.BTP_USERNAME }}
#          export CF_PASSWORD=${{ secrets.BTP_PASSWORD }}
#          export CF_API_URL=${{ secrets.CF_API_URL }}
#          btptf create-json -o ${{ secrets.CF_ORGANIZATION }} -p integrationTestCfOrg.json
#          jq '.BtpResources[] |= (.Values |= sort)' integrationTestCfOrg.json > temp.json && mv temp.json integrationTestCfOrg.json
#          diff <(jq -S . integrationTestCfOrg.json) <(jq -S . integration-test/exporter-reference-data/json-inventory/integrationTestCfOrgReference.json) || echo "JSON inventory for Cloud Foundry Org is not as expected"
#
  test-export-by-json:
    name: Integration Test Export by JSON
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache: true

      - name: Download dependencies
        run: go mod download

      - name: Install Terraform exporter CLI
        run: make install

      - name: Setup Terraform CLI
        uses: hashicorp/setup-terraform@v3.1.2
        with:
          terraform_version: ${{ env.TF_VERSION }}
          terraform_wrapper: false

      - name: "Setup Node.js"
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Export by JSON for Directory
        run: |
          echo "====================================="
          echo "Export by JSON for Directory"
          echo "====================================="
          export BTP_USERNAME=${{ secrets.BTP_USERNAME }}
          export BTP_PASSWORD=${{ secrets.BTP_PASSWORD }}
          export BTP_GLOBALACCOUNT=${{ secrets.BTP_GLOBALACCOUNT }}
          btptf export-by-json -d ${{ secrets.BTP_DIRECTORY }} -p integration-test/exporter-reference-data/import-by-json/integrationTestDirectoryCurated.json -c directory-export-by-json
          echo "====================================="
          echo "Executing state import for Directory"
          echo "====================================="
          terraform -chdir=directory-export-by-json init
          terraform -chdir=directory-export-by-json apply -auto-approve
          echo "====================================="
          echo "Preparing state file for Directory in JSON format"
          echo "====================================="
          terraform -chdir=directory-export-by-json show -json > directory-export-by-json-state.json
          echo '${{ secrets.DIRECTORY_EXPORT_BY_JSON_REF}}' | base64 -d > directory-export-by-json-state-reference.json
          echo "====================================="
          echo "Execute comparison of state files for Directory"
          echo "====================================="
          node .github/scripts/compareJson.js directory-export-by-json-state.json directory-export-by-json-state-reference.json

#  test-export-by-resource:
#    name: Integration Test Export by JSON
#    runs-on: ubuntu-latest
#    timeout-minutes: 5
#    steps:
#      - name: Checkout repository
#        uses: actions/checkout@v4
#
#      - name: Setup Go
#        uses: actions/setup-go@v5
#        with:
#          go-version-file: 'go.mod'
#          cache: true
#
#      - name: Download dependencies
#        run: go mod download
#
#      - name: Install Terraform exporter CLI
#        run: make install
#
#      - name: Setup Terraform CLI
#        uses: hashicorp/setup-terraform@v3.1
#        with:
#          terraform_version: ${{ env.TF_VERSION }}
#          terraform_wrapper: false


      # Execute the export by resource for directory with curated inventory
      # Execute Diff against reference file
      # Execute the export by resource for subaccount with curated inventory
      # Execute Diff against reference file
      # Execute the export by resource for CF org with curated inventory
      # Execute Diff against reference file
