name: Integration Test

on:
  workflow_dispatch:
  workflow_call:

permissions:
  contents: read
  issues: write

env:
  TF_VERSION: 1.10.5

jobs:
  test-json-inventory:
    name: Integration Test JSON Inventory
    runs-on: ubuntu-latest
    timeout-minutes: 10
    outputs:
      output_dir_json_inventory: ${{ steps.json-inventory-directory.outputs.result }}
      output_subacount_json_inventory: ${{ steps.json-inventory-subaccount.outputs.result }}
      output_cforg_json_inventory: ${{ steps.json-inventory-cforg.outputs.result }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache: false

      - name: Download dependencies
        run: |
          go mod download
          go mod tidy

      - name: Install Terraform Exporter CLI
        run: make install

      - name: Setup Terraform CLI
        uses: hashicorp/setup-terraform@v3.1.2
        with:
          terraform_version: ${{ env.TF_VERSION }}
          terraform_wrapper: false

      - name: JSON inventory for Directory
        id: json-inventory-directory
        run: |
          trap 'exit_code=$?; if [ $exit_code -ne 0 ]; then echo "result=failure" >> "$GITHUB_OUTPUT"; fi' EXIT
          export BTP_USERNAME=${{ secrets.BTP_USERNAME }}
          export BTP_PASSWORD=${{ secrets.BTP_PASSWORD }}
          export BTP_GLOBALACCOUNT=${{ secrets.BTP_GLOBALACCOUNT }}
          btptf create-json -d ${{ secrets.BTP_DIRECTORY }} -p integrationTestDirectory.json
          jq '.BtpResources[] |= (.Values |= sort)' integrationTestDirectory.json > temp.json && mv temp.json integrationTestDirectory.json
          diff <(jq -S . integrationTestDirectory.json) <(jq -S . integration-test/exporter-reference-data/json-inventory/integrationTestDirectoryReference.json)
          echo "result=success" >> "$GITHUB_OUTPUT"

      - name: JSON inventory for Subaccount
        id: json-inventory-subaccount
        if: ${{ success() }} || ${{ failure() }}
        run: |
          trap 'exit_code=$?; if [ $exit_code -ne 0 ]; then echo "result=failure" >> "$GITHUB_OUTPUT"; fi' EXIT
          export BTP_USERNAME=${{ secrets.BTP_USERNAME }}
          export BTP_PASSWORD=${{ secrets.BTP_PASSWORD }}
          export BTP_GLOBALACCOUNT=${{ secrets.BTP_GLOBALACCOUNT }}
          btptf create-json -s ${{ secrets.BTP_SUBACCOUNT }} -p integrationTestSubaccount.json
          jq '.BtpResources[] |= (.Values |= sort)' integrationTestSubaccount.json > temp.json && mv temp.json integrationTestSubaccount.json
          diff <(jq -S . integrationTestSubaccount.json) <(jq -S . integration-test/exporter-reference-data/json-inventory/integrationTestSubaccountReference.json) || echo "JSON inventory for subaccount is not as expected"
          echo "result=success" >> "$GITHUB_OUTPUT"

      - name: JSON inventory for Cloud Foundry Org
        id: json-inventory-cforg
        if: ${{ success() }} || ${{ failure() }}
        run: |
          trap 'exit_code=$?; if [ $exit_code -ne 0 ]; then echo "result=failure" >> "$GITHUB_OUTPUT"; fi' EXIT
          export CF_USER=${{ secrets.BTP_USERNAME }}
          export CF_PASSWORD=${{ secrets.BTP_PASSWORD }}
          export CF_API_URL=${{ secrets.CF_API_URL }}
          btptf create-json -o ${{ secrets.CF_ORGANIZATION }} -p integrationTestCfOrg.json
          jq '.BtpResources[] |= (.Values |= sort)' integrationTestCfOrg.json > temp.json && mv temp.json integrationTestCfOrg.json
          diff <(jq -S . integrationTestCfOrg.json) <(jq -S . integration-test/exporter-reference-data/json-inventory/integrationTestCfOrgReference.json) || echo "JSON inventory for Cloud Foundry Org is not as expected"
          echo "result=success" >> "$GITHUB_OUTPUT"

  test-export-by-json:
    name: Integration Test Export by JSON
    runs-on: ubuntu-latest
    timeout-minutes: 10
    outputs:
      output_dir_export_by_json: ${{ steps.export-by-json-directory.outputs.result }}
      output_subacount_export_by_json: ${{ steps.export-by-json-subaccount.outputs.result }}
      output_cforg_export_by_json: ${{ steps.export-by-json-cforg.outputs.result }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache: false

      - name: Download dependencies
        run: |
          go mod download
          go mod tidy

      - name: Install Terraform exporter CLI
        run: make install

      - name: Setup Terraform CLI
        uses: hashicorp/setup-terraform@v3.1.2
        with:
          terraform_version: ${{ env.TF_VERSION }}
          terraform_wrapper: false

      - name: "Setup Node.js"
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Export by JSON for Directory
        id: export-by-json-directory
        run: |
          trap 'exit_code=$?; if [ $exit_code -ne 0 ]; then echo "result=failure" >> "$GITHUB_OUTPUT"; fi' EXIT
          echo "====================================="
          echo "Export by JSON for Directory"
          echo "====================================="
          export BTP_USERNAME=${{ secrets.BTP_USERNAME }}
          export BTP_PASSWORD=${{ secrets.BTP_PASSWORD }}
          export BTP_GLOBALACCOUNT=${{ secrets.BTP_GLOBALACCOUNT }}
          btptf export-by-json -d ${{ secrets.BTP_DIRECTORY }} -p integration-test/exporter-reference-data/import-by-json/integrationTestDirectoryCurated.json -c directory-export-by-json
          echo "====================================="
          echo "Executing state import for Directory"
          echo "====================================="
          terraform -chdir=directory-export-by-json init
          terraform -chdir=directory-export-by-json apply -auto-approve
          echo "Preparing state file for Directory in JSON format"
          terraform -chdir=directory-export-by-json show -json > directory-export-by-json-state.json
          echo '${{ secrets.DIRECTORY_EXPORT_BY_JSON_REF}}' | base64 -d > directory-export-by-json-state-reference.json
          echo "====================================="
          echo "Execute comparison of state files for Directory"
          echo "====================================="
          node .github/scripts/compareJson.js directory-export-by-json-state-reference.json directory-export-by-json-state.json
          echo "result=success" >> "$GITHUB_OUTPUT"

      - name: Export by JSON for Subaccount
        id: export-by-json-subaccount
        if: ${{ success() }} || ${{ failure() }}
        run: |
          trap 'exit_code=$?; if [ $exit_code -ne 0 ]; then echo "result=failure" >> "$GITHUB_OUTPUT"; fi' EXIT
          echo "====================================="
          echo "Export by JSON for Subaccount"
          echo "====================================="
          export BTP_USERNAME=${{ secrets.BTP_USERNAME }}
          export BTP_PASSWORD=${{ secrets.BTP_PASSWORD }}
          export BTP_GLOBALACCOUNT=${{ secrets.BTP_GLOBALACCOUNT }}
          btptf export-by-json -s ${{ secrets.BTP_SUBACCOUNT }} -p integration-test/exporter-reference-data/import-by-json/integrationTestSubaccountCurated.json -c subaccount-export-by-json
          echo "====================================="
          echo "Executing state import for Subaccount"
          echo "====================================="
          terraform -chdir=subaccount-export-by-json init
          terraform -chdir=subaccount-export-by-json apply -auto-approve
          echo "Preparing state file for Subaccount in JSON format"
          terraform -chdir=subaccount-export-by-json show -json > subaccount-export-by-json-state.json
          echo '${{ secrets.SUBACCOUNT_EXPORT_BY_JSON_REF}}' | base64 -d > subaccount-export-by-json-state-reference.json
          echo "====================================="
          echo "Execute comparison of state files for Subaccount"
          echo "====================================="
          node .github/scripts/compareJson.js subaccount-export-by-json-state-reference.json subaccount-export-by-json-state.json
          echo "result=success" >> "$GITHUB_OUTPUT"

      - name: Export by JSON for Cloud Foundry Organization
        id: export-by-json-cforg
        if: ${{ success() }} || ${{ failure() }}
        run: |
          trap 'exit_code=$?; if [ $exit_code -ne 0 ]; then echo "result=failure" >> "$GITHUB_OUTPUT"; fi' EXIT
          echo "====================================="
          echo "Export by JSON for CF Organization"
          echo "====================================="
          export CF_USER=${{ secrets.BTP_USERNAME }}
          export CF_PASSWORD=${{ secrets.BTP_PASSWORD }}
          export CF_API_URL=${{ secrets.CF_API_URL }}
          btptf export-by-json -o ${{ secrets.CF_ORGANIZATION }} -p integration-test/exporter-reference-data/import-by-json/integrationTestCfOrgCurated.json -c cforg-export-by-json
          echo "====================================="
          echo "Executing state import for CF Organization"
          echo "====================================="
          terraform -chdir=cforg-export-by-json init
          terraform -chdir=cforg-export-by-json apply -auto-approve
          echo "Preparing state file for CF Organization in JSON format"
          terraform -chdir=cforg-export-by-json show -json > cforg-export-by-json-state.json
          echo '${{ secrets.CFORG_EXPORT_BY_JSON_REF}}' | base64 -d > cforg-export-by-json-state-reference.json
          echo "====================================="
          echo "Execute comparison of state files for CF Organization"
          echo "====================================="
          node .github/scripts/compareJson.js cforg-export-by-json-state-reference.json cforg-export-by-json-state.json
          echo "result=success" >> "$GITHUB_OUTPUT"

  test-export-by-resource:
    name: Integration Test Export by Ressource
    runs-on: ubuntu-latest
    timeout-minutes: 10
    outputs:
      output_dir_export_by_res: ${{ steps.export-by-resource-directory.outputs.result }}
      output_subacount_export_by_res: ${{ steps.export-by-resource-subaccount.outputs.result }}
      output_cforg_export_by_res: ${{ steps.export-by-resource-cforg.outputs.result }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache: false

      - name: Download dependencies
        run: |
          go mod download
          go mod tidy

      - name: Install Terraform exporter CLI
        run: make install

      - name: Setup Terraform CLI
        uses: hashicorp/setup-terraform@v3.1.2
        with:
          terraform_version: ${{ env.TF_VERSION }}
          terraform_wrapper: false

      - name: "Setup Node.js"
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Export by Resource for Directory
        id: export-by-resource-directory
        run: |
          trap 'exit_code=$?; if [ $exit_code -ne 0 ]; then echo "result=failure" >> "$GITHUB_OUTPUT"; fi' EXIT
          echo "====================================="
          echo "Export by Resource for Directory"
          echo "====================================="
          export BTP_USERNAME=${{ secrets.BTP_USERNAME }}
          export BTP_PASSWORD=${{ secrets.BTP_PASSWORD }}
          export BTP_GLOBALACCOUNT=${{ secrets.BTP_GLOBALACCOUNT }}
          btptf export -d ${{ secrets.BTP_DIRECTORY }} -c directory-export-by-resource -r=directory
          echo "====================================="
          echo "Executing state import for Directory"
          echo "====================================="
          terraform -chdir=directory-export-by-resource init
          terraform -chdir=directory-export-by-resource apply -auto-approve
          echo "Preparing state file for Directory in JSON format"
          terraform -chdir=directory-export-by-resource show -json > directory-export-by-resource-state.json
          echo '${{ secrets.DIRECTORY_EXPORT_BY_RESOURCE_REF}}' | base64 -d > directory-export-by-resource-state-reference.json
          echo "====================================="
          echo "Execute comparison of state files for Directory"
          echo "====================================="
          node .github/scripts/compareJson.js directory-export-by-resource-state-reference.json directory-export-by-resource-state.json
          echo "result=success" >> "$GITHUB_OUTPUT"


      - name: Export by Resource for Subaccount
        id: export-by-resource-subaccount
        if: ${{ success() }} || ${{ failure() }}
        run: |
          trap 'exit_code=$?; if [ $exit_code -ne 0 ]; then echo "result=failure" >> "$GITHUB_OUTPUT"; fi' EXIT
          echo "====================================="
          echo "Export by Resource for Subaccount"
          echo "====================================="
          export BTP_USERNAME=${{ secrets.BTP_USERNAME }}
          export BTP_PASSWORD=${{ secrets.BTP_PASSWORD }}
          export BTP_GLOBALACCOUNT=${{ secrets.BTP_GLOBALACCOUNT }}
          btptf export -s ${{ secrets.BTP_SUBACCOUNT }} -c subaccount-export-by-resource -r='subaccount,subscriptions'
          echo "====================================="
          echo "Executing state import for Subaccount"
          echo "====================================="
          terraform -chdir=subaccount-export-by-resource init
          terraform -chdir=subaccount-export-by-resource apply -auto-approve
          echo "Preparing state file for Subaccount in JSON format"
          terraform -chdir=subaccount-export-by-resource show -json > subaccount-export-by-resource-state.json
          echo '${{ secrets.SUBACCOUNT_EXPORT_BY_RESOURCE_REF}}' | base64 -d > subaccount-export-by-resource-state-reference.json
          echo "====================================="
          echo "Execute comparison of state files for Subaccount"
          echo "====================================="
          node .github/scripts/compareJson.js subaccount-export-by-resource-state-reference.json subaccount-export-by-resource-state.json
          echo "result=success" >> "$GITHUB_OUTPUT"

      - name: Export by Resource for Cloud Foundry Organization
        id: export-by-resource-cforg
        if: ${{ success() }} || ${{ failure() }}
        run: |
          trap 'exit_code=$?; if [ $exit_code -ne 0 ]; then echo "result=failure" >> "$GITHUB_OUTPUT"; fi' EXIT
          echo "====================================="
          echo "Export by Resource for CF Organization"
          echo "====================================="
          export CF_USER=${{ secrets.BTP_USERNAME }}
          export CF_PASSWORD=${{ secrets.BTP_PASSWORD }}
          export CF_API_URL=${{ secrets.CF_API_URL }}
          btptf export -o ${{ secrets.CF_ORGANIZATION }} -c cforg-export-by-resource -r='spaces'
          echo "====================================="
          echo "Executing state import for CF Organization"
          echo "====================================="
          terraform -chdir=cforg-export-by-resource init
          terraform -chdir=cforg-export-by-resource apply -auto-approve
          echo "Preparing state file for CF Organization in JSON format"
          terraform -chdir=cforg-export-by-resource show -json > cforg-export-by-resource-state.json
          echo '${{ secrets.CFORG_EXPORT_BY_RESOURCE_REF}}' | base64 -d > cforg-export-by-resource-state-reference.json
          echo "====================================="
          echo "Execute comparison of state files for CF Organization"
          echo "====================================="
          node .github/scripts/compareJson.js cforg-export-by-resource-state-reference.json cforg-export-by-resource-state.json
          echo "result=success" >> "$GITHUB_OUTPUT"

  test-result-handling:
    name: Handle Test Results
    runs-on: ubuntu-latest
    needs: [test-json-inventory, test-export-by-json, test-export-by-resource]
    steps:
    - name: Build Test Result
      run: |
        echo '${{ toJSON(needs.test-json-inventory.outputs) }}' > inventory.json
        echo '${{ toJSON(needs.test-export-by-json.outputs) }}' > export-by-json.json
        echo '${{ toJSON(needs.test-export-by-resource.outputs) }}' > export-by-resource.json
        jq -s '.[0] + .[1] + .[2]' inventory.json export-by-json.json export-by-resource.json > out.json
        if jq -e 'to_entries[] | select(.value == "failure")' out.json > /dev/null; then
          echo "failure=true" >> "$GITHUB_ENV"
          jq -r 'to_entries[] | "## " + .key + "\n" + .value' out.json > out.md
        else
          echo "failure=false" >> "$GITHUB_ENV"
        fi

    - name: Create or update issue for broken links
      if: env.failure == 'true'
      uses: peter-evans/create-issue-from-file@v5
      with:
          title: Regression Test Report
          content-filepath: out.md
          labels: automated issue
