# Terraform exporter pre-release check workflow.
# This workflow can be manually triggered and executes the check workflows
# needed to publish a release
name: Terraform Exporter Pre-Release Check

on:
  workflow_dispatch:

jobs:
  call-workflow-test:
    uses: ./.github/workflows/test.yml
    secrets: inherit
  call-workflow-regression-test:
    uses: ./.github/workflows/integration-test.yml
    secrets: inherit
    permissions:
      contents: read
      issues: write
