name: Update Brew Formula

on:
  workflow_dispatch:

permissions:
  contents: write
  id-token: write

jobs:
  build-msi:
    runs-on: windows-latest

    steps:
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
      - name: Install WiX
        run: dotnet tool install --global wix
      - name: Get latest release tag
        id: latest_release
        shell: pwsh
        run: |
          $tag = (gh release list --limit 1 --repo "${{ github.repository }}" | Select-String -Pattern '^\S+' -AllMatches).Matches.Value
          echo "tag=$tag" >> $env:GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout code at latest tag
        uses: actions/checkout@v4
        with:
          # ref: ${{ steps.latest_release.outputs.tag }}
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache: false

      - name: Generate product_code GUID
        id: guid
        shell: pwsh
        run: |
          $guid = [guid]::NewGuid().ToString().ToUpper()
          echo "PRODUCT_CODE={$guid}" >> $env:GITHUB_ENV

      - name: Build MSI only
        uses: goreleaser/goreleaser-action@v5
        with:
          version: "v2.7.0"
          distribution: goreleaser-pro
          args: release --clean --snapshot --config=goreleaser-msi.yaml --timeout=60m
        env:
          GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}
          PRODUCT_CODE: ${{ env.PRODUCT_CODE }}
